# Site settings
title: 기록 남기기
url: "https://johklo.github.io"
baseurl: ""
description: >
    JK Blog

# My information
email: john.chu.kim@yahoo.com
author: John Kim
profile: John
github_username: johklo
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: roundrush
  shortname: roundrush
utterances:
  repo: johklo/johklo.github.io
  issue-term: url
  label: Comment
  branch: master

google_analytics:
  ua: SAMPLE-VALUE
  encrypted_ua: THIS-IS-SAMPLE-VALUE

google_adsense:
  client: SAMPLE-VALUE

blame: "https://github.com/johklo/johklo.github.io/blame/master/_wiki"
edit: "https://github.com/johklo/johklo.github.io/edit/master/_wiki"
issue: "https://github.com/johklo/johklo.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
